services:
  - type: web
    name: maria-bot
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: MINI_APP_URL
        sync: false
      - key: BITRIX_WEBHOOK
        value: https://b24.maria-irk.ru/rest/4399/v5j4d5tofsxwrerz/
